# Generated by Django 5.0.1 on 2024-12-31 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
